### ISSUE TITLE
com.gluonhq:gluonfx-gradle-plugin cannot be found

### ISSUE THREAD

**Issue by nlisker** [gluonhq/gluonfx-gradle-plugin#120]
If I use the new `gluonfx` plugin:

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'com.gluonhq:gluonfx-gradle-plugin:0.9.0'
    }
}
apply plugin: 'com.gluonhq.gluonfx-gradle-plugin'
```

I get `Plugin with id 'com.gluonhq:gluonfx-gradle-plugin' not found.` during the build.

However, with the `client` plugin it works:

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'com.gluonhq:client-gradle-plugin:0.1.42'
    }
}
apply plugin: 'com.gluonhq.client-gradle-plugin'
```

Using the DSL I get the same result.

**Comment by schlegel11** [comment]
Hello :smiley: 

hmm this is odd. I can't reproduce the issue.
But the default plugin site [https://plugins.gradle.org/m2/com/gluonhq/gluonfx-gradle-plugin/0.9.0/](https://plugins.gradle.org/m2/com/gluonhq/gluonfx-gradle-plugin/0.9.0/) is reachable for you right?

Which version of gradle do you use?  Im using _"gradle-6.9-all"_ -> you can find it in your "{YOUR_PROJECT}/gradle/wrapper/gradle-wrapper.properties" file -> "distributionUrl=https://services.gradle.org/distributions/gradle-6.9-all.zip"

**Comment by nlisker** [comment]
> But the default plugin site https://plugins.gradle.org/m2/com/gluonhq/gluonfx-gradle-plugin/0.9.0/ is reachable for you right?

Yes

> Which version of gradle do you use?

7.1

> Does it work if you remove your "GRADLE_USER_HOME" dir e.g. in "{YOUR_HOME_DIR}/.gradle" and redownload everything so dependencies and gradle wrapper?

No, same issue.

Here is the stack trace:

```
* What went wrong:
A problem occurred evaluating project ':MyProject'.
> Plugin with id 'com.gluonhq:gluonfx-gradle-plugin' not found.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':MyProject'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
        at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:74)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:74)
        at org.gradle.configuration.BuildOperationScriptPlugin.lambda$apply$0(BuildOperationScriptPlugin.java:62)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:62)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$applyToMutableState$0(DefaultProjectStateRegistry.java:280)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:307)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.applyToMutableState(DefaultProjectStateRegistry.java:279)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:42)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:35)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.lambda$run$0(LifecycleProjectEvaluator.java:100)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$applyToMutableState$0(DefaultProjectStateRegistry.java:280)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.lambda$withProjectLock$3(DefaultProjectStateRegistry.java:340)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:213)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.withProjectLock(DefaultProjectStateRegistry.java:340)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.fromMutableState(DefaultProjectStateRegistry.java:321)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.applyToMutableState(DefaultProjectStateRegistry.java:279)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:91)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:74)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:74)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:63)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:741)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:149)
        at org.gradle.api.internal.project.DefaultProjectStateRegistry$ProjectStateImpl.ensureConfigured(DefaultProjectStateRegistry.java:253)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:41)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:57)
        at org.gradle.configuration.DefaultProjectsPreparer.prepareProjects(DefaultProjectsPreparer.java:50)
        at org.gradle.configuration.BuildTreePreparingProjectsPreparer.prepareProjects(BuildTreePreparingProjectsPreparer.java:64)
        at org.gradle.configuration.BuildOperationFiringProjectsPreparer$ConfigureBuild.run(BuildOperationFiringProjectsPreparer.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:74)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:74)
        at org.gradle.configuration.BuildOperationFiringProjectsPreparer.prepareProjects(BuildOperationFiringProjectsPreparer.java:40)
        at org.gradle.initialization.VintageBuildModelController.prepareProjects(VintageBuildModelController.java:85)
        at org.gradle.initialization.VintageBuildModelController.doBuildStages(VintageBuildModelController.java:69)
        at org.gradle.initialization.VintageBuildModelController.scheduleRequestedTasks(VintageBuildModelController.java:61)
        at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$scheduleRequestedTasks$1(DefaultBuildLifecycleController.java:112)
        at org.gradle.internal.build.DefaultBuildLifecycleController.withModel(DefaultBuildLifecycleController.java:134)
        at org.gradle.internal.build.DefaultBuildLifecycleController.scheduleRequestedTasks(DefaultBuildLifecycleController.java:110)
        at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$scheduleAndRunTasks$0(DefaultBuildTreeLifecycleController.java:62)
        at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.lambda$doBuild$4(DefaultBuildTreeLifecycleController.java:105)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:213)
        at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.doBuild(DefaultBuildTreeLifecycleController.java:99)
        at org.gradle.internal.buildtree.DefaultBuildTreeLifecycleController.scheduleAndRunTasks(DefaultBuildTreeLifecycleController.java:61)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.internal.buildtree.ProblemReportingBuildActionRunner.run(ProblemReportingBuildActionRunner.java:50)
        at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:69)
        at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:90)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
        at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.lambda$execute$0(RootBuildLifecycleBuildActionExecutor.java:40)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:128)
        at org.gradle.launcher.exec.RootBuildLifecycleBuildActionExecutor.execute(RootBuildLifecycleBuildActionExecutor.java:40)
        at org.gradle.internal.buildtree.DefaultBuildTreeContext.execute(DefaultBuildTreeContext.java:40)
        at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.lambda$execute$0(BuildTreeLifecycleBuildActionExecutor.java:40)
        at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:53)
        at org.gradle.launcher.exec.BuildTreeLifecycleBuildActionExecutor.execute(BuildTreeLifecycleBuildActionExecutor.java:40)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:61)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor$3.call(RunAsBuildOperationBuildActionExecutor.java:57)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionExecutor.execute(RunAsBuildOperationBuildActionExecutor.java:57)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecutor.execute(ContinuousBuildActionExecutor.java:103)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecutor.execute(SubscribableBuildActionExecutor.java:64)
        at org.gradle.internal.session.DefaultBuildSessionContext.execute(DefaultBuildSessionContext.java:46)
        at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.lambda$execute$0(BuildSessionLifecycleBuildActionExecuter.java:55)
        at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:69)
        at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:54)
        at org.gradle.tooling.internal.provider.BuildSessionLifecycleBuildActionExecuter.execute(BuildSessionLifecycleBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:63)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:58)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with id 'com.gluonhq:gluonfx-gradle-plugin' not found.
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:144)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:167)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:43)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:98)
        at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:190)
        at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:49)
        at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:37)
        at org.gradle.api.Script$apply$1.callCurrent(Unknown Source)
        at build_aybyq2zikt4cd8kxet4akf7a4.run(C:\Users\Nir\git\Game\GameClientGUI\build.gradle:30)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
        ... 140 more
```

**Comment by abidmaqbool** [comment]
@nlisker Please try to switch to very latest gradle plugin e.g. 1.0.0. I hope it's will be working fine. I think old plugins was not correctly put to maven central repository.

**Comment by nlisker** [comment]
> @nlisker Please try to switch to very latest gradle plugin e.g. 1.0.0. I hope it's will be working fine. I think old plugins was not correctly put to maven central repository.

I tried that too, and the now released 1.0.1, same issues. I noticed that on the main page, on the right, it says that the latest release is:
0.0.10
on Jun 25, 2019

I'm not sure if something happened after the name change that made things not work.

**Comment by schlegel11** [comment]
Hi

I think the issue has nothing to do specifically with this plugin. The plugin repository should be fine and is correctly defined in this block:
```groovy
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
```

> I noticed that on the main page, on the right, it says that the latest release is:
0.0.10

Yes right :smile: I think the version is just wrongly labeled with the _"latest"_ label.

Currently I have no clue what issue it could be. Maybe you have to setup an example project in a public repository so that we can have a look.
Maybe you have to try another gradle version or another dev environment via a VM or docker or anything else. For me it looks fine and if I use the exact same code/buildscript block from your first comment here, everything is working fine.

**Comment by jperedadnr** [comment]
Latest release is 1.0.1. GitHub requires a "manual" of the release to label it "latest", but you can find it here: 
https://github.com/gluonhq/gluonfx-gradle-plugin/releases or https://github.com/gluonhq/gluonfx-gradle-plugin/releases/tag/1.0.1

The plugin is released: https://plugins.gradle.org/m2/com/gluonhq/gluonfx-gradle-plugin/1.0.1/

Can you try `./gradlew  --refresh-dependencies gluonfx:run`

**Comment by nlisker** [comment]
I'm attaching my minimal test project.

When I comment out the lines
`classpath "com.gluonhq:gluonfx-gradle-plugin:1.0.1"`
`apply plugin: 'com.gluonhq:gluonfx-gradle-plugin'`

I get

```
$ ./gradlew --refresh-dependencies


> Connecting to Daemon<-------------> 0% CONFIGURING [96ms]> root project > Resolve dependencies of detachedConfiguration1<-------------> 0% CONFIGURING [190ms]<-------------> 0% CONFIGURING [283ms]<-------------> 0% CONFIGURING [395ms]<-------------> 0% CONFIGURING [488ms]<-------------> 0% CONFIGURING [582ms]<-------------> 0% CONFIGURING [691ms]<-------------> 0% CONFIGURING [783ms]<-------------> 0% CONFIGURING [892ms]<-------------> 0% CONFIGURING [985ms]<-------------> 0% CONFIGURING [1s]> root project > Resolve dependencies of detachedConfiguration1 > org.openjfx.j> root project > Resolve dependencies of detachedConfiguration1> root project > Resolve dependencies of :classpath<-------------> 0% CONFIGURING [2s]<-------------> 0% CONFIGURING [3s]<-------------> 0% CONFIGURING [4s]<-------------> 0% CONFIGURING [5s]<-------------> 0% CONFIGURING [6s]> root project > Resolve dependencies of :classpath > moduleplugin-1.8.2.module<-------------> 0% CONFIGURING [7s]> root project > Resolve dependencies of :classpath<-------------> 0% CONFIGURING [8s]<-------------> 0% CONFIGURING [9s]<-------------> 0% CONFIGURING [10s]> root project > Resolve files of :classpath<-------------> 0% CONFIGURING [11s]
> Configure project :
Project : => no module-info.java found

> Task :help

Welcome to Gradle 7.1.

To run a build, run gradlew <task> ...

To see a list of available tasks, run gradlew tasks

To see a list of command-line options, run gradlew --help

To see more detail about a task, run gradlew help --task <task>

For troubleshooting, visit https://help.gradle.org

BUILD SUCCESSFUL in 21s
1 actionable task: 1 executed
```

When I instead comment out the lines:
`classpath "com.gluonhq:client-gradle-plugin:0.1.42"`
`apply plugin: "com.gluonhq.client-gradle-plugin"`

I get

```
$ ./gradlew --refresh-dependencies


> Connecting to Daemon<-------------> 0% CONFIGURING [68ms]> root project > Resolve dependencies of detachedConfiguration1<-------------> 0% CONFIGURING [162ms]<-------------> 0% CONFIGURING [256ms]<-------------> 0% CONFIGURING [365ms]<-------------> 0% CONFIGURING [457ms]<-------------> 0% CONFIGURING [568ms]<-------------> 0% CONFIGURING [661ms]<-------------> 0% CONFIGURING [756ms]> root project > Resolve dependencies of detachedConfiguration1 > org.openjfx.j<-------------> 0% CONFIGURING [865ms]> root project > Resolve dependencies of detachedConfiguration1<-------------> 0% CONFIGURING [959ms]<-------------> 0% CONFIGURING [1s]> root project > Resolve dependencies of :classpath<-------------> 0% CONFIGURING [2s]<-------------> 0% CONFIGURING [3s]<-------------> 0% CONFIGURING [4s]<-------------> 0% CONFIGURING [5s]<-------------> 0% CONFIGURING [6s]> root project > Resolve dependencies of :classpath > moduleplugin-1.8.2.module<-------------> 0% CONFIGURING [7s]> root project > Resolve dependencies of :classpath<-------------> 0% CONFIGURING [8s]<-------------> 0% CONFIGURING [9s]> root project > Resolve files of :classpath<-------------> 0% CONFIGURING [10s]<-------------> 0% CONFIGURING [11s]> root project
> Configure project :
Project : => no module-info.java found

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Nir\git\gradleTest\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating root project 'gradleTest'.
> Plugin with id 'com.gluonhq:gluonfx-gradle-plugin' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

```

If you don't see the same issue, then I have no idea. I already deleted the whole `.gradle` folder.

[gradleTest.zip](https://github.com/gluonhq/gluonfx-gradle-plugin/files/6677743/gradleTest.zip)

**Comment by jperedadnr** [comment]
I can reproduce the issue (just running `sh gradlew tasks`).

If I modify the build.gradle file to:
```
plugins {
	id 'org.openjfx.javafxplugin' version '0.0.10'
        id 'com.gluonhq.gluonfx-gradle-plugin' version '1.0.1'
}

wrapper {
	gradleVersion = '7.1'
}
```

it works fine for me.

**Comment by schlegel11** [comment]
That's a good example project.
For me it works also if I don't change anything but the line 24 has a typo:
`//apply plugin: 'com.gluonhq:gluonfx-gradle-plugin'`

change it to (so don't use a colon ":" but a dot "."):

`apply plugin: 'com.gluonhq.gluonfx-gradle-plugin'`

and it will work.

**Comment by nlisker** [comment]
> change it to (so don't use a colon ":" but a dot "."):

Good catch. The sample project work.

Now if I add

```
repositories {
	mavenCentral()
	maven {
		url 'https://nexus.gluonhq.com/nexus/content/repositories/releases'
	}
}

gluonClient {
	attachConfig {
		version = "4.0.11"
		services 'display', 'lifecycle', 'statusbar', 'storage', 'device'
	}
}
```

I get

`Could not find method gluonClient() for arguments [build_3fc1am632x743o3a9t7odid6v$_run_closure1@67f6863e] on root project 'gradleTest' of type org.gradle.api.Project.`

while it works for the colder plugin. Was this changed? What is the alternative?

**Comment by jperedadnr** [comment]
The extension was renamed from `gluonClient` to `gluonfx`.

https://github.com/gluonhq/gluonfx-gradle-plugin/commit/95d2fc26c38ebadda9dd525f3c7468b50053ca73#diff-416a18e8fae32d738210ca435b4d1dd69cc6ad009326a18ab7b77ec75f0f6f02L72

**Comment by nlisker** [comment]
It's all working now, thanks all!

I suggest to update the README to include the new names, especially for those who migrate like I did.
