### ISSUE TITLE
:HelloFX:nativeRun Graphics Device initialization failed for :  es2, sw

### ISSUE THREAD

**Issue by ctoabidmaqbool** [gluonhq/gluonfx-gradle-plugin#190]
Hi! I am trying to native compile, lilnk and run on [Gluon-Samples-Gralde/HelloFX](https://github.com/gluonhq/gluon-samples-gradle/tree/master/HelloFX) with no luck.

I already have:

```
maqboolstudiopc@MSC-30:/mnt/d/JavaFx-Android/gluon-samples-gradle$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

maqboolstudiopc@MSC-30:/mnt/d/JavaFx-Android/gluon-samples-gradle$ ld --version
GNU ld (GNU Binutils for Ubuntu) 2.34
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

maqboolstudiopc@MSC-30:/mnt/d/JavaFx-Android/gluon-samples-gradle$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

maqboolstudiopc@MSC-30:/mnt/d/JavaFx-Android/gluon-samples-gradle$ g++ --version
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

the error:

```
maqboolstudiopc@MSC-30:/mnt/d/JavaFx-Android/gluon-samples-gradle$ ./gradlew :HelloFX:nativeBuild :HelloFX:nativeRun --stacktrace

> Task :HelloFX:nativeCompile
[Sun May 26 11:44:32 PKT 2024][INFO] ==================== COMPILE TASK ====================
[Sun May 26 11:44:32 PKT 2024][INFO] We will now compile your code for x86_64-linux-linux. This may take some time.

[Sun May 26 11:44:35 PKT 2024][INFO] [SUB] Warning: Ignoring server-mode native-image argument --no-server.
[Sun May 26 11:44:39 PKT 2024][INFO] [SUB] Warning: Invalid option --add-exports org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED provided by command line. Specified module 'org.graalvm.nativeimage.builder' is unknown.
[Sun May 26 11:45:06 PKT 2024][INFO] [SUB] ========================================================================================================================
[Sun May 26 11:45:06 PKT 2024][INFO] [SUB] GraalVM Native Image: Generating 'hellofx.hellofx' (shared library)...
[Sun May 26 11:45:06 PKT 2024][INFO] [SUB] ========================================================================================================================
[Sun May 26 11:45:07 PKT 2024][INFO] [SUB] [GluonFeature] enabled for config com.oracle.svm.hosted.FeatureImpl$IsInConfigurationAccessImpl@13e698c7
[Sun May 26 11:45:15 PKT 2024][INFO] [SUB] GluonFeature enabled in setup com.oracle.svm.hosted.FeatureImpl$DuringSetupAccessImpl@1000d54d
[Sun May 26 11:45:20 PKT 2024][INFO] [SUB] [1/7] Initializing...                                                                                   (39.6s @ 0.15GB)
[Sun May 26 11:45:20 PKT 2024][INFO] [SUB]  Version info: 'GraalVM 22.1.0.1 Java 17 CE'
[Sun May 26 11:45:20 PKT 2024][INFO] [SUB]  C compiler: gcc (linux, x86_64, 9.4.0)
[Sun May 26 11:45:20 PKT 2024][INFO] [SUB]  Garbage collector: Serial GC
[Sun May 26 11:45:20 PKT 2024][INFO] [SUB]  1 user-provided feature(s)
[Sun May 26 11:45:20 PKT 2024][INFO] [SUB]   - com.gluonhq.substrate.feature.GluonFeature
[Sun May 26 11:48:50 PKT 2024][INFO] [SUB] [2/7] Performing analysis...  [**********]                                                             (208.2s @ 1.91GB)
[Sun May 26 11:48:50 PKT 2024][INFO] [SUB]   11,284 (90.08%) of 12,526 classes reachable
[Sun May 26 11:48:50 PKT 2024][INFO] [SUB]   19,817 (65.89%) of 30,075 fields reachable
[Sun May 26 11:48:50 PKT 2024][INFO] [SUB]   55,159 (63.00%) of 87,551 methods reachable
[Sun May 26 11:48:50 PKT 2024][INFO] [SUB]      636 classes,   109 fields, and 1,943 methods registered for reflection
[Sun May 26 11:48:50 PKT 2024][INFO] [SUB]      112 classes,   140 fields, and   182 methods registered for JNI access
[Sun May 26 11:49:00 PKT 2024][INFO] [SUB] [3/7] Building universe...                                                                               (9.9s @ 2.65GB)
[Sun May 26 11:49:13 PKT 2024][INFO] [SUB] [4/7] Parsing methods...      [****]                                                                    (12.9s @ 2.49GB)
[Sun May 26 11:49:40 PKT 2024][INFO] [SUB] [5/7] Inlining methods...     [****]                                                                    (26.1s @ 1.06GB)
[Sun May 26 11:52:26 PKT 2024][INFO] [SUB] [6/7] Compiling methods...    [*************]                                                          (165.9s @ 1.81GB)
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB]
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB] ------------------------------------------------------------------------------------------------------------------------
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB]                         46.1s (9.3% of total time) in 60 GCs | Peak RSS: 4.38GB | CPU load: 3.43
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB] ------------------------------------------------------------------------------------------------------------------------
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB] Produced artifacts:
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB]  /mnt/d/JavaFx-Android/gluon-samples-gradle/HelloFX/build/gluonfx/x86_64-linux/gvm/HelloFX/hellofx.hellofx.h (header)
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB]  /mnt/d/JavaFx-Android/gluon-samples-gradle/HelloFX/build/gluonfx/x86_64-linux/gvm/HelloFX/graal_isolate.h (header)
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB]  /mnt/d/JavaFx-Android/gluon-samples-gradle/HelloFX/build/gluonfx/x86_64-linux/gvm/HelloFX/hellofx.hellofx_dynamic.h (header)
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB]  /mnt/d/JavaFx-Android/gluon-samples-gradle/HelloFX/build/gluonfx/x86_64-linux/gvm/HelloFX/graal_isolate_dynamic.h (header)
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB]  /mnt/d/JavaFx-Android/gluon-samples-gradle/HelloFX/build/gluonfx/x86_64-linux/gvm/HelloFX/hellofx.hellofx.build_artifacts.txt
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB] ========================================================================================================================
[Sun May 26 11:52:51 PKT 2024][INFO] [SUB] Finished generating 'hellofx.hellofx' in 8m 10s.

> Task :HelloFX:nativeLink
[Sun May 26 11:52:52 PKT 2024][INFO] ==================== LINK TASK ====================

> Task :HelloFX:nativeRun
[Sun May 26 11:53:09 PKT 2024][INFO] ==================== RUN TASK ====================

[Sun May 26 11:53:11 PKT 2024][INFO] [SUB] May 26, 2024 11:53:11 AM com.sun.javafx.application.PlatformImpl startup
[Sun May 26 11:53:11 PKT 2024][INFO] [SUB] WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @71c7db30'
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB] Graphics Device initialization failed for :  es2, sw
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB] Error initializing QuantumRenderer: no suitable pipeline found
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB] java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:253)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:263)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at java.lang.Thread.run(Thread.java:833)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB] Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      ... 3 more
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB] Exception in thread "main" java.lang.RuntimeException: No toolkit found
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:275)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:290)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at java.lang.Thread.run(Thread.java:833)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
[Sun May 26 11:53:12 PKT 2024][INFO] [SUB]      at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 8m 47s
6 actionable tasks: 6 executed
```

before are the logs:
[gluonfx.zip](https://github.com/gluonhq/gluonfx-gradle-plugin/files/15446485/gluonfx.zip)

**Comment by ctoabidmaqbool** [comment]
I think, the same issue here: https://github.com/gluonhq/gluonfx-gradle-plugin/issues/57

**Comment by ctoabidmaqbool** [comment]
Okey! I have solve the problem! the trick was enableSwRendering to true.

 gluonfx {
        target = 'host'
        if (project.hasProperty('target')) {
            target = project.getProperty('target')
        }
        graalvmHome = "/mnt/d/Programs/graalvm-svm-java17-linux-gluon-22.1.0.1-Final"
        enableSwRendering = true
    }
Note: This is also mentioned in [docs](https://docs.gluonhq.com/#_software_rendering) too!
