### ISSUE TITLE
wasting time with nonsense Caused by: java.io.IOException: Current GraalVM version (22) not supported. Please upgrade to 22.1 or higher

### ISSUE THREAD

**Issue by crowlogic** [gluonhq/gluonfx-gradle-plugin#198]
this piece of crap tells me to install 22.1,so I do, and it says I didn't

```
[crow@c15 20240909-06:54:52AM]~/todo$ export GRAALVM_HOME=/jvm/graalvm-ce-java17-22.1.0
gradle nativePackage

Caused by: java.io.IOException: Current GraalVM version (22) not supported.
Please upgrade to 22.1 or higher
        at com.gluonhq.substrate.model.InternalProjectConfiguration.checkGraalVMVersion(InternalProjectConfiguration.java:497)
        at com.gluonhq.substrate.model.InternalProjectConfiguration.<init>(InternalProjectConfiguration.java:124)
        at com.gluonhq.substrate.SubstrateDispatcher.<init>(SubstrateDispatcher.java:377)
        at com.gluonhq.gradle.tasks.ConfigBuild.build(ConfigBuild.java:92)
        ... 119 more


BUILD FAILED in 476ms
3 actionable tasks: 1 executed, 2 up-to-date

```

```
[crow@c15 20240909-06:56:56AM]~/todo$ cat build.gradle

plugins {
    id 'java-library'
    id 'maven-publish'
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gluonhq.gluonfx-gradle-plugin' version '1.0.23'
}

group = 'org.arblib'
version = '0.99.3'
description = 'todo'
java.sourceCompatibility = JavaVersion.VERSION_21

javafx {
    version = "17.0.12" 
    modules = [ 'javafx.swing', 'javafx.controls', 'javafx.fxml', 'javafx.graphics' ]  
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = uri('https://jitpack.io') }
    maven { url = uri('https://oss.sonatype.org/content/repositories/releases') }
    maven { url = uri('https://raw.github.com/SpinyOwl/repo/releases') }
    maven { url = uri('https://maven.jzy3d.org/releases/') }
    maven { url = uri('https://amelentev.github.io/mvnrepo/') }
    maven { url = uri('https://repo.maven.apache.org/maven2/') }
    maven { url = uri('https://download.oracle.com/maven') }
}

dependencies {

    api 'org.openjfx:javafx-base:22.0.1'
    api 'org.openjfx:javafx-swing:22.0.1'
    api 'org.openjfx:javafx-fxml:22.0.1'
   
    api 'org.controlsfx:controlsfx:11.2.0'
    
}

task createDesktopFile {
    doLast {
        def desktopFile = new File("${buildDir}/TODO.desktop")
        desktopFile.text = """[Desktop Entry]
Type=Application
Name=TODO
Exec=${projectDir}/bin/todo
Icon=${projectDir}/src/main/resources/TODO.png
Terminal=false
Categories=Utility;
"""
    }    
}

task installDesktopFile(type: Copy) {
    dependsOn createDesktopFile
    from "${buildDir}/TODO.desktop"
    into "${System.getProperty('user.home')}/.local/share/applications"
}

build.finalizedBy createDesktopFile
build.finalizedBy installDesktopFile

tasks.withType(Javadoc) {
    options.addStringOption('source', '21') 
    options.addBooleanOption('Xdoclint:none', true) 
    options.addBooleanOption('quiet', true)         
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE;
     from('src/main/resources') {
        include '**/*'
    }
}

application {
 mainClassName = 'arb.viz.TODO'
}


javafx {
    version = '17.0.12'
    modules = ['javafx.controls', 'javafx.fxml']
}


gluonfx {
    graalvmHome = '/jvm/graalvm-svm-java17-linux-gluon-22.0.0.3-Final'
    target = "android"
}
    


java {
    withSourcesJar()
    modularity.inferModulePath.set(true)
}

tasks.withType(JavaCompile) {
    options.fork = true
    options.forkOptions.jvmArgs += ['-ea']
}


task createClasspathManifest {
    doLast {
        def classpathEntries = configurations.runtimeClasspath.collect { it.getAbsolutePath() }.join(':')
        def manifestFile = file('class.path')
        manifestFile.text = "${classpathEntries}\n"
    }
}

tasks.build.dependsOn createClasspathManifest


publishing {
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}

processResources {
   duplicatesStrategy = DuplicatesStrategy.EXCLUDE;
   from('src/main/resources') {
        include '**/*'
    }
    into 'build/classes/java/main'
}
```

**Comment by crowlogic** [comment]
oh haha nevermind, it was ignoring GRAALVM_HOME because it was set in the build.gradle file
